### ISSUE TITLE
How to Close a session?

### ISSUE THREAD

**Issue by portablesoft** [Tatsh/sendspace-cli#2]
Hi,

When I using the sendspace-cli, I encountered the following error:

> SendspaceRESTAPIError: Status not "ok", error: Too many sessions open for your user account.  Please close previous sessions.

How to colse a session? Thanks.

**Comment by Tatsh** [comment]
I do not know if there is a way to do that, other than waiting for the session to time out.

The client is designed to store your session ID at `~/.sendspace-session` and use it in subsequent runs. https://github.com/Tatsh/sendspace-cli/blob/master/bin/sendspace#L40 When the session expires a new one should generate automatically from Sendspace and be saved to this file.

If this file does not get saved properly no error is reported on that unless the write fails (this is because the file is not expected to exist on first run).
